version: 2

sources:
  - name: "{{ var('source_name') }}"
    database: "{{ var('source_database') }}"
    schema:  "{{ var('source_schema') }}"
    tables:
      - name: Members
      - name: Member_Eligibility
      - name: Medical_Claims_Header
      - name: medical_claims_line
      - name: Medical_Claims_Dx
      - name: Medical_Claims_Procedures
      - name: Claim_Level_Value_Add_DRG