version: 2

sources:
  - name: "{{ var('source_name') }}"
    database: "{{ var('source_database') }}"
    schema:  "{{ var('source_schema') }}"
    tables:
      - name: member_demographics
      - name: member_eligibility
      - name: medical_claims_header
      - name: medical_claims_line
      - name: medical_claims_dx
      - name: medical_claims_procedures
      - name: diagnosis_related_groups_drg