version: 2

sources:
  - name: COAPCD
    tables:
      - name: Medical_Claims_Dx
      - name: Medical_Claims_Procedures
      - name: Members
      - name: Member_Eligibility
      - name: Medical_Claims_Header
      - name: medical_claims_line
      - name: Claim_Level_Value_Add_DRG
